// <auto-generated />
using System;
using HyHeroesWebAPI.Infrastructure.Persistence.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace HyHeroesWebAPI.Presentation.Migrations
{
    [DbContext(typeof(HyHeroesDbContext))]
    [Migration("20210130133741_EdsmsRequestCooldown")]
    partial class EdsmsRequestCooldown
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.ActualValueOfOneKredit", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<decimal>("Value")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("ActualValueOfOneKredit");

                    b.HasData(
                        new
                        {
                            Id = new Guid("ed15c4b2-e9bc-4e89-ad77-cda2793278e5"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 816, DateTimeKind.Local).AddTicks(7393),
                            IsActive = true,
                            Value = 2m
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.BarionBillingAddress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BarionTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<string>("City")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Country")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Region")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Street")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Street2")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Street3")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Zip")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("BarionTransactionId")
                        .IsUnique();

                    b.ToTable("BarionBillingAddresses");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.BarionTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FinishDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsFinished")
                        .HasColumnType("tinyint(1)");

                    b.Property<double>("KreditAmount")
                        .HasColumnType("double");

                    b.Property<Guid>("PaymentId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<int>("State")
                        .HasColumnType("int");

                    b.Property<double>("TotalCost")
                        .HasColumnType("double");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("BarionTransactions");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.BillingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BillingDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ProductName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("UserEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoAdoszam")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoAzonosito")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoCim")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoIrsz")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoMegjegyzes")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoNev")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoPostazasiCim")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoPostazasiIrsz")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoPostazasiNev")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoPostazasiTelepules")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoSendEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoTelefonszam")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VevoTelepules")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("BillingTransactions");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.BlacklistedIP", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("BanDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("IP")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsIPBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("BlacklistedIPs");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.ClientIdentity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("BaseValue")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ValidatorHash")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ValidatorSalt")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("ClientIdentities");

                    b.HasData(
                        new
                        {
                            Id = new Guid("37cf392f-6681-410e-b1e5-8674472d9d6d"),
                            BaseValue = "bQY0QnNkr4ch0cAR1sBM6uZr+IFWzt4N",
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(6431),
                            ExpirationDate = new DateTime(2021, 1, 30, 15, 37, 40, 817, DateTimeKind.Local).AddTicks(7711),
                            IsActive = true,
                            UserId = new Guid("5de99496-dbbd-4ce5-9445-6d453b46d145"),
                            ValidatorHash = "whQv8pQfvmULOXU3szzZo3kgPcGDa5vL",
                            ValidatorSalt = "IFch0cAbQ46uZ0Wr+QnNkrBMR1sYzt4N"
                        },
                        new
                        {
                            Id = new Guid("ca1c172d-30bd-4813-a374-ea6e70416387"),
                            BaseValue = "bQY0QnNkr4ch0cAR1sBM6uZr+IFWzt4N",
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(8725),
                            ExpirationDate = new DateTime(2021, 1, 30, 15, 37, 40, 817, DateTimeKind.Local).AddTicks(8769),
                            IsActive = true,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5"),
                            ValidatorHash = "whQv8pQfvmULOXU3szzZo3kgPcGDa5vL",
                            ValidatorSalt = "IFch0cAbQ46uZ0Wr+QnNkrBMR1sYzt4N"
                        },
                        new
                        {
                            Id = new Guid("813a6344-53d6-4818-b05a-bdc66794e01f"),
                            BaseValue = "bQY0QnNkr4ch0cAR1sBM6uZr+IFWzt4N",
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(8791),
                            ExpirationDate = new DateTime(2021, 1, 30, 15, 37, 40, 817, DateTimeKind.Local).AddTicks(8794),
                            IsActive = true,
                            UserId = new Guid("96bb6ed1-38e2-4bd7-b6d7-989ec78f5698"),
                            ValidatorHash = "whQv8pQfvmULOXU3szzZo3kgPcGDa5vL",
                            ValidatorSalt = "IFch0cAbQ46uZ0Wr+QnNkrBMR1sYzt4N"
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.EDSMSPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ActivationCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("KreditPurchaseId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("KreditPurchaseId");

                    b.ToTable("EDSMSPurchases");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.EmailVerificationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ActivationCode")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ActivationTimeStamp")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EmailToVerify")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActivated")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("EmailVerificationCodes");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.FailedBillingTransaction", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("BillingTransactionId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FailDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KreditAmount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("BillingTransactionId");

                    b.ToTable("FailedTransactions");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.GameServer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsServerRunning")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("ServerName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("GameServers");

                    b.HasData(
                        new
                        {
                            Id = new Guid("3d7af1ec-503a-4d4d-a8d2-4fd36afc7bc9"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 812, DateTimeKind.Local).AddTicks(6074),
                            IsActive = true,
                            IsServerRunning = true,
                            ServerName = "GTA"
                        },
                        new
                        {
                            Id = new Guid("c03a6241-eaa2-4e02-a28c-f2ea195e3d2c"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 815, DateTimeKind.Local).AddTicks(5582),
                            IsActive = true,
                            IsServerRunning = true,
                            ServerName = "Survival"
                        },
                        new
                        {
                            Id = new Guid("9c16379c-d84a-439a-b626-e4df9833729d"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 815, DateTimeKind.Local).AddTicks(5633),
                            IsActive = true,
                            IsServerRunning = true,
                            ServerName = "Skyblock"
                        },
                        new
                        {
                            Id = new Guid("7acebdda-879d-4294-8387-5495fc8e9fc8"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 815, DateTimeKind.Local).AddTicks(5639),
                            IsActive = true,
                            IsServerRunning = false,
                            ServerName = "RPG"
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.JatekfizetesRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CallDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CallerUserId")
                        .HasColumnType("char(36)");

                    b.Property<string>("ClientIP")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActivationSuccessful")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("CallerUserId");

                    b.ToTable("JatekfizetesRequests");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.KreditGift", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KreditGiftAmount")
                        .HasColumnType("int");

                    b.Property<Guid>("ReceiverUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid>("SenderUserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ReceiverUserId");

                    b.HasIndex("SenderUserId");

                    b.ToTable("KreditGifts");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.KreditPurchase", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CurrencyValue")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KreditValue")
                        .HasColumnType("int");

                    b.Property<int>("PaymentType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("KreditPurchases");

                    b.HasData(
                        new
                        {
                            Id = new Guid("97a1393f-ba76-4945-a673-faa12a270a63"),
                            CreationDate = new DateTime(2020, 9, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2785),
                            CurrencyValue = 2000,
                            IsActive = true,
                            KreditValue = 1000,
                            PaymentType = 1,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("e925c8fe-945e-45e7-ae03-7b886b31c45a"),
                            CreationDate = new DateTime(2020, 9, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2894),
                            CurrencyValue = 5000,
                            IsActive = true,
                            KreditValue = 2500,
                            PaymentType = 1,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("b2861633-eecb-4629-87a6-b977fb00af85"),
                            CreationDate = new DateTime(2020, 10, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2908),
                            CurrencyValue = 1000,
                            IsActive = true,
                            KreditValue = 500,
                            PaymentType = 1,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("fdd65315-19d3-4510-a2a4-b049e5adc76c"),
                            CreationDate = new DateTime(2020, 10, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2917),
                            CurrencyValue = 2000,
                            IsActive = true,
                            KreditValue = 1000,
                            PaymentType = 1,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("dd892cda-e1a7-459e-8e6e-0a5a2c0c6696"),
                            CreationDate = new DateTime(2020, 11, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2924),
                            CurrencyValue = 6000,
                            IsActive = true,
                            KreditValue = 3000,
                            PaymentType = 1,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("73428da6-76e4-4dba-b0df-4216867b38b5"),
                            CreationDate = new DateTime(2020, 12, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2932),
                            CurrencyValue = 3000,
                            IsActive = true,
                            KreditValue = 1500,
                            PaymentType = 1,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("91c13a84-077d-4f40-b77d-1efe153f1e2a"),
                            CreationDate = new DateTime(2020, 9, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2939),
                            CurrencyValue = 330,
                            IsActive = true,
                            KreditValue = 330,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("cad70061-292a-45de-ad54-1d33df313c6c"),
                            CreationDate = new DateTime(2020, 9, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2947),
                            CurrencyValue = 500,
                            IsActive = true,
                            KreditValue = 508,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("0a31bc2d-f6d9-406e-98af-0b144d4f9574"),
                            CreationDate = new DateTime(2020, 10, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2955),
                            CurrencyValue = 2000,
                            IsActive = true,
                            KreditValue = 2032,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("5a5e69c6-8e51-4315-8515-c466a9758421"),
                            CreationDate = new DateTime(2020, 10, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2962),
                            CurrencyValue = 330,
                            IsActive = true,
                            KreditValue = 330,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("da75c546-4f4b-43c8-88ee-2069674311d2"),
                            CreationDate = new DateTime(2020, 10, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2972),
                            CurrencyValue = 330,
                            IsActive = true,
                            KreditValue = 330,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("324d9763-76e3-47c5-a9f3-15843de46b36"),
                            CreationDate = new DateTime(2020, 11, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2979),
                            CurrencyValue = 500,
                            IsActive = true,
                            KreditValue = 508,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("91071812-446e-48dd-b37f-dd3504ca0cb4"),
                            CreationDate = new DateTime(2020, 11, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2987),
                            CurrencyValue = 500,
                            IsActive = true,
                            KreditValue = 508,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("e79cd9bc-b363-4787-ba39-4ac53e221e49"),
                            CreationDate = new DateTime(2020, 12, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(2994),
                            CurrencyValue = 500,
                            IsActive = true,
                            KreditValue = 508,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("aea8df4b-7954-490c-a0a5-25baffee56c4"),
                            CreationDate = new DateTime(2020, 12, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3001),
                            CurrencyValue = 500,
                            IsActive = true,
                            KreditValue = 508,
                            PaymentType = 0,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("adac06ba-5ed1-4d95-8b10-ec8a74dc28d6"),
                            CreationDate = new DateTime(2020, 9, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3009),
                            CurrencyValue = 1000,
                            IsActive = true,
                            KreditValue = 500,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("d589f2f2-5d2e-4a7b-8636-d1b1feb5c5cb"),
                            CreationDate = new DateTime(2020, 10, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3016),
                            CurrencyValue = 1000,
                            IsActive = true,
                            KreditValue = 500,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("989ea933-bea1-4dbb-9a2b-ee40f5b691fa"),
                            CreationDate = new DateTime(2020, 10, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3024),
                            CurrencyValue = 2000,
                            IsActive = true,
                            KreditValue = 1000,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("cd2d5071-0486-43f5-aafe-4ba5f9ab770f"),
                            CreationDate = new DateTime(2020, 11, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3033),
                            CurrencyValue = 3000,
                            IsActive = true,
                            KreditValue = 1500,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("0a37f0f7-418a-40b0-8ca7-6e3ecb90c233"),
                            CreationDate = new DateTime(2020, 11, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3041),
                            CurrencyValue = 3000,
                            IsActive = true,
                            KreditValue = 1500,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("3067464c-4fb4-40b3-9f65-650fa1f82bdb"),
                            CreationDate = new DateTime(2020, 11, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3048),
                            CurrencyValue = 3000,
                            IsActive = true,
                            KreditValue = 1500,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("efacfd61-88cb-4c00-85ad-e8a475a7b763"),
                            CreationDate = new DateTime(2020, 11, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3056),
                            CurrencyValue = 1000,
                            IsActive = true,
                            KreditValue = 500,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("3e8af8d8-5556-4a56-bd45-94cc6337ce2f"),
                            CreationDate = new DateTime(2020, 12, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3063),
                            CurrencyValue = 4000,
                            IsActive = true,
                            KreditValue = 2000,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("6cfc386b-224b-4865-8f2d-30a70e870dd5"),
                            CreationDate = new DateTime(2020, 12, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(3071),
                            CurrencyValue = 3000,
                            IsActive = true,
                            KreditValue = 1500,
                            PaymentType = 2,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.MassKreditActivationCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Code")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KreditValue")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("MassKreditActivationCodes");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.MassKreditUserActivation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("ActivationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("MassKreditActivationCodeId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("MassKreditActivationCodeId");

                    b.HasIndex("UserId");

                    b.ToTable("MassKreditUserActivations");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.News", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("FormattedNews")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Preview")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<Guid>("PublisherUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("PublisherUserId");

                    b.ToTable("News");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2ae0ca66-ff78-4572-8bb9-4d2b79965980"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 34, 20, 818, DateTimeKind.Local).AddTicks(9790),
                            FormattedNews = "Ez itt a hír tartalma.",
                            IsActive = true,
                            Preview = "Ez a hír előnézeti szövege.",
                            PublisherUserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5"),
                            Title = "Teszt Hír #1"
                        },
                        new
                        {
                            Id = new Guid("5060ca3b-941e-4d43-af29-2f3d37c7b7a3"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 35, 10, 819, DateTimeKind.Local).AddTicks(356),
                            FormattedNews = "Ez itt a hír tartalma.",
                            IsActive = true,
                            Preview = "Ez a hír előnézeti szövege.",
                            PublisherUserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5"),
                            Title = "Teszt Hír #2"
                        },
                        new
                        {
                            Id = new Guid("0c0dc174-465a-40d3-8baa-4f3ee21a3224"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 36, 0, 819, DateTimeKind.Local).AddTicks(374),
                            FormattedNews = "Ez itt a hír tartalma.",
                            IsActive = true,
                            Preview = "Ez a hír előnézeti szövege.",
                            PublisherUserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5"),
                            Title = "Teszt Hír #3"
                        },
                        new
                        {
                            Id = new Guid("21445d66-8a25-49ad-9619-14a70aceb8ad"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 36, 50, 819, DateTimeKind.Local).AddTicks(381),
                            FormattedNews = "Ez itt a hír tartalma.",
                            IsActive = true,
                            Preview = "Ez a hír előnézeti szövege.",
                            PublisherUserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5"),
                            Title = "Teszt Hír #4"
                        },
                        new
                        {
                            Id = new Guid("be43a406-701a-4a52-94ed-aceab482e534"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 819, DateTimeKind.Local).AddTicks(389),
                            FormattedNews = "Ez itt a hír tartalma.",
                            IsActive = true,
                            Preview = "Ez a hír előnézeti szövege.",
                            PublisherUserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5"),
                            Title = "Teszt Hír #5"
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.OnlinePlayerState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GameServerId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("OnlinePlayerCount")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameServerId");

                    b.ToTable("OnlinePlayerStates");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PasswordResetCode", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Code")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("PasswordResetCodes");

                    b.HasData(
                        new
                        {
                            Id = new Guid("c8fd1d08-f7ec-4587-8105-fda33d5cc97e"),
                            Code = new Guid("309f1fad-f3ba-4924-a401-5de509d6ae27"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(6323),
                            IsActive = true,
                            IsUsed = false,
                            UserId = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5")
                        },
                        new
                        {
                            Id = new Guid("669b9c18-2d8f-45cf-8710-b19692e2cdce"),
                            Code = new Guid("ef2fbc7a-33c0-4162-939b-c2a32c41153c"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(7336),
                            IsActive = true,
                            IsUsed = false,
                            UserId = new Guid("96bb6ed1-38e2-4bd7-b6d7-989ec78f5698")
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PayPalIPNMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("AddressCity")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressCountry")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressCountryCode")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressState")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressStatus")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressStreet")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("AddressZip")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("Charset")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Custom")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("FirstName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("HandlingAmount")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ItemName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ItemNumber")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("LastName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("McCurrency")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("McFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("McGross")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("NotifyVersion")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PayerEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PayerId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PayerStatus")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("PaymentDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("PaymentFee")
                        .HasColumnType("decimal(65,30)");

                    b.Property<decimal>("PaymentGross")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PaymentType")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ProtectionEligibility")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.Property<string>("ReceiverEmail")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ReceiverId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ResidenceCountry")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("Shipping")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<decimal>("Tax")
                        .HasColumnType("decimal(65,30)");

                    b.Property<string>("TestIpn")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TransactionSubject")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("TxnId")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("VerifySign")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("PayPalIPNMessages");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PayPalTransactionRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRequestProcessed")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("RequesterUserId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("RequesterUserId");

                    b.ToTable("PayPalTransactionRequests");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.Product", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Description")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("InGameActivatorCommand")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("InGameDeactivatorCommand")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRank")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("OneTimeCommand")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PermanentPrice")
                        .HasColumnType("int");

                    b.Property<int>("PricePerMonth")
                        .HasColumnType("int");

                    b.Property<Guid?>("ProductCategoryId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("ProductCategoryId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0a7642b3-7d07-4751-8a86-ad5fec0d9c04"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(967),
                            Description = "test description",
                            ImageUrl = "http://localhost:4200/assets/img/add-icon.png",
                            InGameActivatorCommand = "activate",
                            InGameDeactivatorCommand = "deactivate",
                            IsActive = true,
                            IsRank = true,
                            Name = "VIP rang",
                            OneTimeCommand = "onetime command",
                            PermanentPrice = 2000,
                            PricePerMonth = 1000,
                            ProductCategoryId = new Guid("894cf24d-9bf2-4935-9b31-4d1614f1cee0")
                        },
                        new
                        {
                            Id = new Guid("67ef9139-9d51-48b9-baee-5eb06108949f"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(5434),
                            Description = "test description",
                            ImageUrl = "http://localhost:4200/assets/img/add-icon.png",
                            InGameActivatorCommand = "activate",
                            InGameDeactivatorCommand = "deactivate",
                            IsActive = true,
                            IsRank = true,
                            Name = "Bajnok rang",
                            OneTimeCommand = "onetime command",
                            PermanentPrice = 6000,
                            PricePerMonth = 3000,
                            ProductCategoryId = new Guid("894cf24d-9bf2-4935-9b31-4d1614f1cee0")
                        },
                        new
                        {
                            Id = new Guid("6de974e7-f321-4686-b301-5d716c55aba0"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(5542),
                            Description = "test description",
                            ImageUrl = "http://localhost:4200/assets/img/add-icon.png",
                            InGameActivatorCommand = "activate",
                            InGameDeactivatorCommand = "deactivate",
                            IsActive = true,
                            IsRank = true,
                            Name = "Elit rang",
                            OneTimeCommand = "onetime command",
                            PermanentPrice = 10000,
                            PricePerMonth = 5000,
                            ProductCategoryId = new Guid("894cf24d-9bf2-4935-9b31-4d1614f1cee0")
                        },
                        new
                        {
                            Id = new Guid("3bbf1afa-9e59-4aec-a58a-75948db2e771"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(5549),
                            Description = "test description",
                            ImageUrl = "http://localhost:4200/assets/img/add-icon.png",
                            InGameActivatorCommand = "activate",
                            InGameDeactivatorCommand = "deactivate",
                            IsActive = true,
                            IsRank = true,
                            Name = "SzuperElit rang",
                            OneTimeCommand = "onetime command",
                            PermanentPrice = 14000,
                            PricePerMonth = 8000,
                            ProductCategoryId = new Guid("894cf24d-9bf2-4935-9b31-4d1614f1cee0")
                        },
                        new
                        {
                            Id = new Guid("6c5dbb53-f3d0-41a6-a772-aa2fed96840e"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(5600),
                            Description = "test description",
                            ImageUrl = "http://localhost:4200/assets/img/add-icon.png",
                            InGameActivatorCommand = "activate",
                            InGameDeactivatorCommand = "deactivate",
                            IsActive = true,
                            IsRank = true,
                            Name = "HiperSzuperElit rang",
                            OneTimeCommand = "onetime command",
                            PermanentPrice = 16000,
                            PricePerMonth = 10000,
                            ProductCategoryId = new Guid("894cf24d-9bf2-4935-9b31-4d1614f1cee0")
                        },
                        new
                        {
                            Id = new Guid("e9501d0e-8c73-4851-802e-e813018fcfe1"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(5606),
                            Description = "test description",
                            ImageUrl = "http://localhost:4200/assets/img/add-icon.png",
                            InGameActivatorCommand = "activate",
                            InGameDeactivatorCommand = "deactivate",
                            IsActive = true,
                            IsRank = true,
                            Name = "ExtraSzuperElit rang",
                            OneTimeCommand = "onetime command",
                            PermanentPrice = 20000,
                            PricePerMonth = 16000,
                            ProductCategoryId = new Guid("894cf24d-9bf2-4935-9b31-4d1614f1cee0")
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.ProductCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("CategoryName")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsUsed")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("Priority")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("ProductCategories");

                    b.HasData(
                        new
                        {
                            Id = new Guid("894cf24d-9bf2-4935-9b31-4d1614f1cee0"),
                            CategoryName = "Rangok",
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(9424),
                            IsActive = true,
                            IsUsed = false,
                            Priority = 1
                        },
                        new
                        {
                            Id = new Guid("5d32fedf-28f9-4bc9-9899-4bacbbe9ea28"),
                            CategoryName = "Egyéb",
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 818, DateTimeKind.Local).AddTicks(325),
                            IsActive = true,
                            IsUsed = false,
                            Priority = 2
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PurchaseState", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("GameServerId")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsActivationVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsExpirationVerified")
                        .HasColumnType("tinyint(1)");

                    b.Property<Guid>("PurchasedProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.HasIndex("GameServerId");

                    b.HasIndex("PurchasedProductId");

                    b.ToTable("PurchaseStates");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PurchasedProduct", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOverwrittenByOtherRank")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsRepeatable")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("KreditSpentOn")
                        .HasColumnType("int");

                    b.Property<DateTime>("LastPurchaseDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("ProductId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.Property<int>("ValidityPeriodInMonths")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ProductId");

                    b.HasIndex("UserId");

                    b.ToTable("PurchasedProducts");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("PermissionLevel")
                        .HasColumnType("int");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.HasKey("Id");

                    b.ToTable("Roles");

                    b.HasData(
                        new
                        {
                            Id = new Guid("77dc6e7e-a188-4174-9752-8014cba152e8"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 816, DateTimeKind.Local).AddTicks(8742),
                            IsActive = true,
                            Name = "User",
                            PermissionLevel = 1
                        },
                        new
                        {
                            Id = new Guid("779126ee-2c1c-4eef-8eec-4ff6463e17aa"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(387),
                            IsActive = true,
                            Name = "Admin",
                            PermissionLevel = 2
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Currency")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<int>("HyCoin")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsBanned")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("LastAuthenticationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastAuthenticationIp")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<string>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<DateTime>("RegistrationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime?>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasColumnType("varchar(255) CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasAlternateKey("UserName");

                    b.HasIndex("RoleId");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = new Guid("5de99496-dbbd-4ce5-9445-6d453b46d145"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(1142),
                            Currency = 1000000,
                            Email = "martinmarkus0@gmail.com",
                            HyCoin = 10000,
                            IsActive = true,
                            IsBanned = false,
                            LastAuthenticationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(2857),
                            LastAuthenticationIp = "localhost",
                            PasswordHash = "IFch0cAbQ46uZ0Wr+QnNkrBMR1sYzt4N",
                            PasswordSalt = "6yuhyavedvvwufmjpln1cjuqrm6agpvh",
                            RegistrationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(3772),
                            RoleId = new Guid("779126ee-2c1c-4eef-8eec-4ff6463e17aa"),
                            UserName = "birdemic"
                        },
                        new
                        {
                            Id = new Guid("bf99a9b3-1d1b-4614-9ff7-90a17b1cd9f5"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(5599),
                            Currency = 50000,
                            Email = "birdemic2@gmail.com",
                            HyCoin = 4000,
                            IsActive = true,
                            IsBanned = false,
                            LastAuthenticationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(5661),
                            LastAuthenticationIp = "localhost",
                            PasswordHash = "IFch0cAbQ46uZ0Wr+QnNkrBMR1sYzt4N",
                            PasswordSalt = "6yuhyavedvvwufmjpln1cjuqrm6agpvh",
                            RegistrationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(5676),
                            RoleId = new Guid("779126ee-2c1c-4eef-8eec-4ff6463e17aa"),
                            UserName = "birdemic2"
                        },
                        new
                        {
                            Id = new Guid("96bb6ed1-38e2-4bd7-b6d7-989ec78f5698"),
                            CreationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(5716),
                            Currency = 40000,
                            Email = "hatoska@gmail.com",
                            HyCoin = 3000,
                            IsActive = true,
                            IsBanned = false,
                            LastAuthenticationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(5721),
                            LastAuthenticationIp = "localhost",
                            PasswordHash = "IFch0cAbQ46uZ0Wr+QnNkrBMR1sYzt4N",
                            PasswordSalt = "6yuhyavedvvwufmjpln1cjuqrm6agpvh",
                            RegistrationDate = new DateTime(2021, 1, 30, 14, 37, 40, 817, DateTimeKind.Local).AddTicks(5723),
                            RoleId = new Guid("77dc6e7e-a188-4174-9752-8014cba152e8"),
                            UserName = "hatoska"
                        });
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.BarionBillingAddress", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.BarionTransaction", "BarionTransaction")
                        .WithOne("BarionBillingAddress")
                        .HasForeignKey("HyHeroesWebAPI.ApplicationCore.Entities.BarionBillingAddress", "BarionTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.BarionTransaction", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "User")
                        .WithMany("BarionTransactions")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.ClientIdentity", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.EDSMSPurchase", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.KreditPurchase", "KreditPurchase")
                        .WithMany("EDSMSPurchases")
                        .HasForeignKey("KreditPurchaseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.EmailVerificationCode", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.FailedBillingTransaction", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.BillingTransaction", "BillingTransaction")
                        .WithMany()
                        .HasForeignKey("BillingTransactionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.JatekfizetesRequest", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "CallerUser")
                        .WithMany("JatekfizetesRequests")
                        .HasForeignKey("CallerUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.KreditGift", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "ReceiverUser")
                        .WithMany("ReceivedKreditGifts")
                        .HasForeignKey("ReceiverUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "SenderUser")
                        .WithMany("SentKreditGifts")
                        .HasForeignKey("SenderUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.KreditPurchase", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId");
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.MassKreditUserActivation", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.MassKreditActivationCode", "MassKreditActivationCode")
                        .WithMany("MassKreditUserActivations")
                        .HasForeignKey("MassKreditActivationCodeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.News", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "PublisherUser")
                        .WithMany()
                        .HasForeignKey("PublisherUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.OnlinePlayerState", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.GameServer", "GameServer")
                        .WithMany("OnlinePlayerStates")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PasswordResetCode", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "User")
                        .WithMany("PasswordResetCodes")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PayPalTransactionRequest", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "RequesterUser")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.Product", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.ProductCategory", "ProductCategory")
                        .WithMany("Products")
                        .HasForeignKey("ProductCategoryId")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PurchaseState", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.GameServer", "GameServer")
                        .WithMany("PurchaseStates")
                        .HasForeignKey("GameServerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.PurchasedProduct", "PurchasedProduct")
                        .WithMany("PurchaseStates")
                        .HasForeignKey("PurchasedProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.PurchasedProduct", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.Product", "Product")
                        .WithMany("PurchasedProducts")
                        .HasForeignKey("ProductId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("HyHeroesWebAPI.ApplicationCore.Entities.User", b =>
                {
                    b.HasOne("HyHeroesWebAPI.ApplicationCore.Entities.Role", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
